# [START runtime]
runtime: custom 
env: flex
# [END runtime]

# [START resources]
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

automatic_scaling:
  max_num_instances: 1
# [END resources]

# [START network]
network:
  forwarded_ports:
    - 4242/tcp
# [END network]

# [START handlers]
handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /
    static_dir: build
# [END handlers]
